apiVersion: v1
kind: Service
metadata:
  name: kubeusersservice
spec:
  selector:
    app: kubeusers
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeusersdeploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubeusers
  template:
    metadata:
      labels:
        app: kubeusers
    spec:
      containers:
        - name: kubeuserscontainer
          image: iramgutierrez/userscreator:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb+srv://iramgutzglez:PolaeoVvneDNjYWL@cluster0.pzs2exz.mongodb.net/43375-clase21?retryWrites=true&w=majority
          imagePullPolicy: Always


